#!/bin/sh
#
# This runs the command api
java -cp target/Crosstalk-0.0.1-SNAPSHOT-jar-with-dependencies.jar:libs/XRTB-0.0.1-SNAPSHOT.jar  com.jacamars.dsp.crosstalk.tools.SendCommand $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16}
